### ISSUE TITLE
outputs doubled

### ISSUE THREAD

**Issue by lampie22** [BlueFinBima/DCS-AV-8B-NA-Profile#11]
so i leaded the profile into helios 1.6 and found all the ouputs are doubled 
![doubled outputs](https://user-images.githubusercontent.com/78164879/106168783-96e47a80-6186-11eb-9b6e-88550fbf6cd9.png)
this results in each button being pressed twice when used in game

**Comment by BlueFinBima** [comment]
Hi @lampie22,  good detective work.  This problem (the duplication of bindings) )was seen in the past with older levels of Helios.  I'm pretty sure that we fixed this.   The profile from here https://github.com/BlueFinBima/DCS-AV-8B-NA-Profile/releases/download/V3.0.0/AV-8B.NA.V3.Profile.for.Helios.zip does not contain duplicate bindings. If it grows them again, then it is a Helios problem.

**Comment by lampie22** [comment]
@BlueFinBima thanls for that. i theough id let you know i opened the v3 you linked and then the v4 on my laptop with a clean first time install of helios 1.6 and could not replicate the issue. my main machine that i had the issue with had helios 1.6 installed over an older version with much older versions of the av8b profile. so i suspect something weird happened with helios and the update.

**Comment by BlueFinBima** [comment]
@lampie22 Thanks for following up.  I think the problem persisted into the 1.6 era so the installation of 1.6 might not have been at fault.  My recommendation is that if you make changes to a profile, then back it up in case something unforeseen happens.  Typically a profile jumping in size is a sign that binding have been duplicated.  
Cheers,  Blue
