### ISSUE TITLE
Limited Sync between DCS and Helios-Profile

### ISSUE THREAD

**Issue by joch40** [BlueFinBima/DCS-AV-8B-NA-Profile#8]
Hi,

Great stuff. Especially in the AV-8B as in my configuration the MFDs are so low that I have a lot of mouse-manoeuvring in order to see and access them properly. 
But while general gauges are working I have the following observations: 
•	The MFD Viewport enablement does not  work (although I pressed the lctrl-lalt a / s keys)
•	Input in the UFC disappears very quickly and therefor can not be used
•	States of Buttons (tested with AFC) do not reflect the current state as set in the Main-Window (AFC was set on but showed Off in Helios)
I am running on Open-Beta 2.5.6 (55960) and Helios 1.6.3308. 

Am I doing something wrong??

Best 

Janko

**Comment by BlueFinBima** [comment]
Hi  Janko,
1.  MFD viewports.  Not sure about this. I'll have to fire up it up and take a look. It was working a couple of weeks back when I did the V4 packaging for Helios 1.6.
2. Can you expand on this problem. Text on my UFC stays the same length of time as the sim.
3.  I'll look at the AFC.  Certainly there are a number of the rotary switches whose output bindings are not connected.  My preference is to fix these in Helios rather than manually in the profile, but the downside to this is that it takes a bit longer.  

Give me a bit of time to investigate, but more info on the UFC problem would be helpful.

**Comment by joch40** [comment]
Hi,

I made a screen recordings to illustrate the UFC Problem:

In the video I interact only with the Helios Interface. As you can see interacting with the num keys doesn’t give any response. The same is true for a short press on TCN or AWL. If I press TCN or AWL longer the data fields show up for a short time. But they don’t stay and it is impossible to change the AWL destination. (It stays on the default 1).

Things get a bit better if I interact via the DCS Screen with the UFC first. Data gets shown and stays but interaction via key input is not working. I can send you a second video showing this if you want.

Best


Janko

And please don’t feel pushed by my input. I know that you are doing this for fun and that is how it should stay.


Von: BlueFinBima <notifications@github.com>
Gesendet: Mittwoch, 21. Oktober 2020 10:02
An: BlueFinBima/DCS-AV-8B-NA-Profile <DCS-AV-8B-NA-Profile@noreply.github.com>
Cc: Dr. Janko Jochimsen <Janko.Jochimsen@urios-beratung.de>; Author <author@noreply.github.com>
Betreff: Re: [BlueFinBima/DCS-AV-8B-NA-Profile] Limited Sync between DCS and Helios-Profile (#8)


Hi Janko,

  1.  MFD viewports. Not sure about this. I'll have to fire up it up and take a look. It was working a couple of weeks back when I did the V4 packaging for Helios 1.6.
  2.  Can you expand on this problem. Text on my UFC stays the same length of time as the sim.
  3.  I'll look at the AFC. Certainly there are a number of the rotary switches whose output bindings are not connected. My preference is to fix these in Helios rather than manually in the profile, but the downside to this is that it takes a bit longer.

Give me a bit of time to investigate, but more info on the UFC problem would be helpful.

**Comment by BlueFinBima** [comment]
Hi Janko,  can you attach the videos to this issue please?

**Comment by joch40** [comment]
Hi, I attached one video as a zip file (because it was too big for the mail system). Now I converted it to a lower resolution and attach it. Lets see whether you receive this time. If not I will put the file in the cloud.

Thanks

Janko

Von: BlueFinBima <notifications@github.com>
Gesendet: Samstag, 24. Oktober 2020 13:31
An: BlueFinBima/DCS-AV-8B-NA-Profile <DCS-AV-8B-NA-Profile@noreply.github.com>
Cc: Dr. Janko Jochimsen <Janko.Jochimsen@urios-beratung.de>; Author <author@noreply.github.com>
Betreff: Re: [BlueFinBima/DCS-AV-8B-NA-Profile] Limited Sync between DCS and Helios-Profile (#8)


Hi Janko, can you attach the videos to this issue please?

**Comment by joch40** [comment]
Here are the files.

Thanks Janko
[AV-8B sync problem.zip](https://github.com/BlueFinBima/DCS-AV-8B-NA-Profile/files/5434328/AV-8B.sync.problem.zip)

**Comment by BlueFinBima** [comment]
Thanks for the videos.  I think I've been able to reproduce the problem (at least part of it).  What is happening is that for the pushbuttons you're getting two presses every time you hit the button.  There is an intermittent bug in Helios which can cause a profile to get duplicate bindings, and the AV-8B one in RC4.0.1 is a lot larger than it is supposed to be.  I'll let you know when I have a fixed profile available.

**Comment by BlueFinBima** [comment]
Hi Janko,  RC4.0.2 can be downloaded from https://github.com/BlueFinBima/DCS-AV-8B-NA-Profile/releases/tag/RC4.0.2 .  Please let me know how you get on.

**Comment by joch40** [comment]
Hi,
sorry to say: while the general situation improved a bit the main problems are still present. Again I am attaching two files: 

[AV-8B sync problem season 2.zip](https://github.com/BlueFinBima/DCS-AV-8B-NA-Profile/files/5435901/AV-8B.sync.problem.season.2.zip)

File 2 -1: input is exclusively send to the helios interface.  As you can see normal / short clicks on the control buttons (ALT / AWL) do nothing. A long press shows the data, but only as long as the button is pressed. The selection is not memorized in the background as all subsequent input goes into nowhere. 
File 2- 2: First input is made in DCS. Data shows up correctly and changes can be made via the helios interface. Although the problem with the repeater input persists and renders the input more or less useless. However, if the repeater problem could be solved this would come close to a workaround (at least for me). 

The MFD is still not working. 

Thanks for the effort.

Best

Janko

**Comment by WilloUK** [comment]
just a quick note regards to MFDS not showing, i had changed my keys in DCS , but when i changed them back to LCtrl LAlt A for left MFD and same but S for right MFD and tried again they worked, so mayb try resetting the keys and moddifers  
Might help
WilloUK

**Comment by joch40** [comment]
Hi,

OK slowly we are getting there: 

In the Controls Section 
Right MPCD Export View ON/OFF
Left MPCD Export View ON/OFF
were undefined. (To me default as I haven’t touched it). Setting them to lctl+lalt+a and lctl+lalt+s did the trick. 

However, now the wiered duration and double click problem makes interacting very difficult. Again I made a video to show the problem.

[AV-8B season 3.zip](https://github.com/BlueFinBima/DCS-AV-8B-NA-Profile/files/5436059/AV-8B.season.3.zip)


Thanks for the effort.

Best

Janko

**Comment by BlueFinBima** [comment]
Hi Janko,  what size is the profile now.  It should be around 336kb.  Thanks

**Comment by WilloUK** [comment]
this is the profile that has worked for me, copy the 3 files in yo your Helios profiles and let them ovewrite the ones already there.
when u load up the profile you will notice the flaps panel is missing, lower left of screen.
You should see a .bak file at 330kb , Helios profile at 336kb and a .HPLY at 3kb in the zip below, all been well as im not great with GitHub


[DCS-AV-8B-NA-Profile-RC4.0.2.zip](https://github.com/BlueFinBima/DCS-AV-8B-NA-Profile/files/5439254/DCS-AV-8B-NA-Profile-RC4.0.2.zip)

**Comment by BlueFinBima** [comment]
@WilloUK since there are many variations of set-ups for Helios it is always recommended to install directly from this file https://github.com/BlueFinBima/DCS-AV-8B-NA-Profile/releases/download/RC4.0.2/AV-8B.V4.helios16 and let Profile Explorer guide through the patching of viewports and also setting up the monitors.

Apologies for the missing flaps panel.  Quick fix is to open the profile in Profile Editor, and replace the image which is currently
```{AV-8B}/Images/Flaps Panel.png```
with
``` AV-8B\Flaps Panel.png```

**Comment by WilloUK** [comment]
Thanks BlueFinBima thats good to know, as for flaps panel sorted that just linked it to the image that was missing from the profile.
Once again a big thank you for your help and a great profile for the Harrier
Cheers WilloUK

**Comment by joch40** [comment]
Hi everybody,

the profile WilloUK send works for me very well and so I am 90 % operational. Funnily the profile BlueFinBima published later (4.0.2) doesn’t improve the situation (again at last for me). 
I attach a video that shows operation on the UFC now fine. 
[AV-8B season 4.zip](https://github.com/BlueFinBima/DCS-AV-8B-NA-Profile/files/5441366/AV-8B.season.4.zip)

At the end of the video there are still two little bugs just for information: 

- It is impossible to show the HUD on the left MFD. You see that I press the button. In DCS the HUD is shown on the left MFD but in the Helios profile there is a blank screen. 
- The Course on the right will only increase no matter in what direction you turn the knob. - 

But as I said this is all not critical. 

Best 

Janko

**Comment by BlueFinBima** [comment]
Hi Janko,  I believe that the problems you are experiencing are because the profile is getting duplicate bindings created by Helios.  This is why I was asking for the size of the profile file.  If the profile size is greater than 340Kb, then you are almost certain to have duplicate bindings.  As shipped the profile in 4.0.2 and 4.0.3 only have single bindings, so at some point, Helios must have created the extra bindings.  If the profile you're having problems with is around 340Kb, then there is something else going on.
The HUD not appearing in the MFD is related to the viewport and not the profile.  The HUD does not appear most probably because Razbam chose not to render it in the exported viewport which seems very strange.  You could try asking on the ED forum if anyone else has found a way around this. I have not flown the Harrier for a long time, so if this used to work, then this could just be an unintentional bug which crept in.
Please let me know the filesize of your profile.

**Comment by joch40** [comment]
Hi,
just to verify. Now also the version you uploaded yesterday works. It shows 336 KB. I did not go back to the last not-working version to find out what size this had. If you need this information I can also install the RC1 again. 
So aside of the minor problems that are more less helios-related everything works. 

Thank you again for the project and the support. 

Best 

Janko
